### ISSUE TITLE
dates array

### ISSUE THREAD

**Issue by DeveloperAdam** [nicolasSchirmer/fork-CalendarDateRangePicker-ptbr#1]
Please help me out that how to get the array of dates if i select the start date 2018-12-10 and end date 2018-12-20 so i can get start and end date only but how to get all the rest of the dates between these two dates in an array?

**Comment by nicolasSchirmer** [comment]
This repository is a forced Brazilian Portuguese language fork from [this repo](https://github.com/ArchitShah248/CalendarDateRangePicker).

You can go there for any explanations. Sorry not been able to help.
